name: Zip Chrome Extension and Upload to Release

on:
  release:
    types: [published]
    
permissions:
  contents: write

jobs:
  build-and-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create zip of extension files
        run: |
          mkdir dist
          cp manifest.json dist/
          cp -r icons dist/
          mkdir -p dist/src/content_scripts
          cp src/content_scripts/*.js dist/src/content_scripts/
          cd dist
          zip -r ../ai-chat-exporter.zip .

      - name: Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: ai-chat-exporter.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
