name: Zip Chrome Extension and Upload to Release

on:
  release:
    types: [published]

jobs:
  build-and-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create zip of extension files
        run: |
          mkdir dist
          cp -r manifest.json popup.html popup.js content_script.js icons dist/
          cd dist
          zip -r ../gemini-chat-exporter.zip .

      - name: Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: gemini-chat-exporter.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
